### ISSUE TITLE
[Question] Does gestures support clockwise & anticlockwise gestures for 2/3/4 fingers?

### ISSUE THREAD

**Issue by IceAsteroid** [natask/gestures#15]
Hi, greetings!

The question is as the title. Does gestures support rotate-like gestures?

I couldn't find anything related in the readme page in this repo.

It's awkward, neither of the gesture programs that I found are feature-complete to use for wayland.

Libinput-gestures is complete for all the gestures but lacks continuous functionality, or said threshold for each command of a gesture to execute. The dev of it is also not willing to implement it, sadge :(

Fusuma, on the other hand, finally has the threshold setting for each gesture, but lacks slanted gestures, such as right/left_up and right/left_down. I posted a related issue on fusuma's repo, but it's been probably three weeks long, still no any good news :( Here's the post: https://github.com/iberianpig/fusuma/issues/310

Gestures, however, probably lacks rotate(clockwise) gestures. What a pain in the ass :)

**Comment by natask** [comment]
Hello. Unfortunately no. If you would like to take a crack at implementing rotation gestures, examine [finger_update(self, event)](https://github.com/natask/gestures/blob/3550c6fe599d5f495a5d9a644db7f1087acc8407/gestures#L140C1-L140C36). you would need a criterion for deciding whether the gesture is rotation based. The gesture is represented by a sequence of time stamped data objects consisting of number fingers and each of their x,y coordinates on the touchpad.
