### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by Nazat95** [natask/gestures#3]
Hello,

I just installed this script on Kubuntu 20.04 and all the default gestures works fine. But where is the config file placed so I can edit the defaults? Also why is it placing in the root directory there is nothing there.

Thank you

![Screenshot](https://user-images.githubusercontent.com/25968402/82720234-60fa0880-9c7f-11ea-8cab-70c9ebc03d32.png)

**Comment by natask** [comment]
The config file should be placed under ~/.config/gestures.conf. It seems your $HOME variable, which is what the ~ character  means, is set to /root not /home/$USERNAME. That is why it is placing stuff under /root.

 This is caused either by using root shell, which sets HOME variable among other things, or you have something in .profile or .bashrc setting HOME variable to the /root. Can you verify if your HOME variable is set right? If you just want to change it for the install or uninstall script you can run HOME=/path/to/directory ./install.sh.

if everything is setup right, look under /root/.config/gestures.conf.   run ls -la ~/.config in terminal and you should be able to see it. The reason you couldn't see it with ls or your file explorer becuase .config directory, like all directories and files that start with a . , is hidden. The way to configure the application is under the customization section of the readme.

**Comment by Nazat95** [comment]
Thank you for the help. I reinstalled it without using sudo and now the config is in the right place. I read the readme and still finding the syntax to be confusing. For example I use keyboard shortcut ctrl+shift+Right/Left key to switch between desktops. Would it look like this:

`'4': {
    'l' : {'start': ['evemu_do keydown ctrl', 'evemu_do keydown shift'],'update': {'l': ["evemu_do Left"], 'r': ["evemu_do Right]}, 'end': [], 'rep': ''},`

Thanks

**Comment by natask** [comment]
You will need to do two things. One is  release `ctrl` and `shift` when the gesture ends, i.e, when you remove fingers while executing a gesture. Second, you currently need to keep in all the other properties under the update property as empty arrays ([]). I talk about this in Todos section but I see that I should make this explicit in the customization section. 

The following should work.

`'4' : {'l' : {'start': ['evemu_do keydown ctrl+shift'],'update': {'l': ["evemu_do Left"], 'r': ["evemu_do Right"], 'u': [], 'd': [], 'lu': [], 'rd': [], 'ld': [], 'ru': []}, 'end': ['evemu_do keyup ctrl+shift'], 'rep': ''},
`

It is much better to keep the config file as it is and just update properties of the config object. This means adding or removing strings (commands) from [] of the properties.

The config syntax is hard to see clearly if the file is not zoomed out as well. 

If you have suggestions in improving the README, feel free to comment or pull request.
