### ISSUE TITLE
Annoying Behaviour when Dragging

### ISSUE THREAD

**Issue by Amarjit3** [natask/gestures#4]
There is annoying behaviour present when selecting text in the following way:

I click the touchpad with my left finger, and then select text on Chrome by dragging my right finger along the touchpad (whilst keeping my left finger still pressed on the trackpad). This results in a pinch action.

Is there any way to disable the pinch action if the touchpad has been clicked first? I only want the pinch action to occur if I'm dragging the touchpad, without clicking it.

**Comment by natask** [comment]
I don't select text that way (I double tap and drag with the same finger) so I haven't had this issue. I will look into it. 
I think the easiest solution is having a dead zone for both fingers in which pinch isn't activated.

**Comment by Amarjit3** [comment]
Thank you. The touchpad on my laptop is large, so it's very difficult to drag with one finger.

**Comment by natask** [comment]
@Amarjit3  Sorry for the delay. can you try the latest commit? I will make it a configuration variable after cleaning it up.

**Comment by Amarjit3** [comment]
It works perfectly now - thank you!
